# Generated by Django 5.1.6 on 2025-03-29 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(default='static/assets/img/Code-AI.png', upload_to='static/assets/img')),
            ],
        ),
        migrations.DeleteModel(
            name='posts',
        ),
    ]
