# Generated by Django 5.1.6 on 2025-04-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0002_blogposts_delete_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='image',
            field=models.ImageField(default='assets/img/Code-AI.png', upload_to='assets/img'),
        ),
    ]
