# Generated by Django 5.1.6 on 2025-04-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0003_alter_blogposts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='image',
            field=models.ImageField(upload_to='assets/img'),
        ),
    ]
